"""initial schema

Revision ID: 0646f2521779
Revises: 
Create Date: 2026-07-22 15:18:12.633244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0646f2521779'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('campaign_id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('objective', sa.String(length=50), nullable=False),
    sa.Column('budget_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_table('adsets',
    sa.Column('adset_id', sa.String(length=30), nullable=False),
    sa.Column('campaign_id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('optimization_goal', sa.String(length=100), nullable=False),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('budget_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ),
    sa.PrimaryKeyConstraint('adset_id')
    )
    op.create_table('ads',
    sa.Column('ad_id', sa.String(length=30), nullable=False),
    sa.Column('adset_id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['adset_id'], ['adsets.adset_id'], ),
    sa.PrimaryKeyConstraint('ad_id')
    )
    op.create_table('daily_performance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ad_id', sa.String(length=30), nullable=False),
    sa.Column('delivery_status', sa.String(length=20), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.ad_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'ad_id', name='uq_daily_performance_date_ad')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_performance')
    op.drop_table('ads')
    op.drop_table('adsets')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
