"""add revenue column to daily_performance

Revision ID: c69306a903c0
Revises: 0646f2521779
Create Date: 2026-07-23 09:28:57.326504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c69306a903c0'
down_revision: Union[str, Sequence[str], None] = '0646f2521779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_performance', sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_performance', 'revenue')
    # ### end Alembic commands ###
